language: c
sudo: false
services:
  - docker
install: wget https://github.com/ocaml/ocaml-ci-scripts/raw/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=ocaml-systemd
  matrix:
    - DISTRO="debian-stable" OCAML_VERSION=4.04.2
    - DISTRO="centos-7" OCAML_VERSION=4.05.0
    - DISTRO="debian-unstable" OCAML_VERSION=4.06.0
