language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
sudo: required
before_install:
   - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
   - sudo apt-get update -qq
   - sudo apt-get install libsystemd-daemon-dev libsystemd-journal-dev libsystemd-dev
script: bash -ex .travis-opam.sh
env:
  -  SYSTEMD_BUILD=1 OCAML_VERSION=4.02
  -  SYSTEMD_BUILD=1 OCAML_VERSION=latest

